from tkinter import *
import os
from tkinter import ttk
from tkinter import filedialog
import whois
import subprocess
from time import strftime
from bs4 import BeautifulSoup
import requests
from fpdf import FPDF 
import datetime;

root = Tk()
root.title('Mal-Or-Not')
root.geometry("430x200+630+350")
bg= PhotoImage(file="matrixbg.png")  

my_canvas = Canvas(root, width=200, height=100, bd=0, highlightthickness=0,bg='black')
my_canvas.pack(fill="both", expand=True)
my_canvas.create_image(0,0, image=bg, anchor="nw")

text_key= Label(my_canvas, text="Welcome To", anchor="w", justify=LEFT, font='"Helvetica" 20', bg='black', fg='white').place(relx = 0.5, rely = 0.25, anchor = 'center')
text_key= Label(my_canvas, text="Mal", anchor="w", justify=LEFT, font='"Helvetica" 20', bg='black', fg='#ff8000').place(relx = 0.367, rely = 0.55, anchor = 'center')
text_key= Label(my_canvas, text="-OR-", anchor="w", justify=LEFT, font='"Helvetica" 20', bg='black', fg='white').place(relx = 0.5, rely = 0.55, anchor = 'center')
text_key= Label(my_canvas, text="Not", anchor="w", justify=LEFT, font='"Helvetica" 20', bg='black', fg='lime').place(relx = 0.627, rely = 0.55, anchor = 'center')
text_key= Label(my_canvas, text="Loading...", anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='white').place(relx = 0.92, rely = 0.95, anchor = 'center')

def destroy():
	global data
	subprocess.check_output(["sh","./speedtest.sh"])
	with open ("/tmp/speed_report.txt","r") as f:
		data=f.readline()
	root.destroy()
root.after(2000, destroy)
root.mainloop()

root = Tk()
root.title('Mal-Or-Not')
root.geometry("430x200+630+350")
bg= PhotoImage(file="matrixbg.png")  

my_canvas = Canvas(root, width=200, height=100, bd=0, highlightthickness=0,bg='black')
my_canvas.pack(fill="both", expand=True)
my_canvas.create_image(0,0, image=bg, anchor="nw")

text_key= Label(my_canvas, text="Enter Username:", anchor="w", justify=LEFT, font='"Helvetica" 15', bg='black', fg='white').place(relx = 0.25, rely = 0.3, anchor = 'center')
entry1 = Entry(root, font=("Helvitica",12),width=13, fg="black", bd=0)
entry_window1 = my_canvas.create_window(200,46,anchor='nw', window=entry1)
text_key= Label(my_canvas, text="Enter City:", anchor="w", justify=LEFT, font='"Helvetica" 15', bg='black', fg='white').place(relx = 0.25, rely = 0.5, anchor = 'center')
entry2 = Entry(root, font=("Helvitica",12),width=13, fg="black", bd=0)
entry_window2 = my_canvas.create_window(200,86,anchor='nw', window=entry2)

def storeiden():
	global city, username
	username=entry1.get()
	cityinp=entry2.get()
	city = cityinp+" weather"
	root.destroy()

buttoniden=Button(root, text="Done",font=("times",12),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=storeiden)
buttoniden_window = my_canvas.create_window(180,130, anchor='nw', window=buttoniden)
root.mainloop()

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
 
 
def weather(city):
	global location, weatherf
	city = city.replace(" ", "+")
	res = requests.get(f'https://www.google.com/search?q={city}&oq={city}&aqs=chrome.0.35i39l2j0l4j46j69i60.6128j1j7&sourceid=chrome&ie=UTF-8', headers=headers)
	soup = BeautifulSoup(res.text, 'html.parser')
	location = soup.select('#wob_loc')[0].getText().strip()
	info = soup.select('#wob_dc')[0].getText().strip()
	weather = soup.select('#wob_tm')[0].getText().strip()
	weatherf=weather+"°C, "+info
weather(city)

def makepdf(x,y,resultfromtxt):
	class PDF(FPDF):
	    def header(self):
	    	self.image('pdfbgi.png', 0, 0, 210)
	    	self.set_font('Arial', 'B', 30)
	    	self.cell(80)
	    	self.cell(30, 30, 'Mal-Or-Not', 0, 1, 'C')
	    	self.set_font('Arial', 'U', 25)
	    	if(y=='ip' or y=='url'):
	    		self.cell(190, 10, y.upper()+' Report', 0, 1, 'C')
	    	else:
	    		self.cell(190, 10, y.capitalize()+' Report', 0, 1, 'C')
	    	self.ln(20)

	    def footer(self):
	        self.set_y(-20)
	        self.set_font('Arial', 'I', 8)
	        self.cell(0, 5, "Report generated at: "+txs, 0, 1, 'L')
	        self.cell(0, 5, "Report generated by: "+username, 0, 1, 'L')
	        self.cell(0, 5, "Location: "+location, 0, 0, 'L')
	        self.cell(0, 5, 'Page ' + str(self.page_no()) + '/{nb}', 0, 1, 'R')
	        self.set_text_color(127, 127, 127)
	        self.cell(0, 5, "© 2022 Mal-Or-Not, All rights reserved.", 0, 0, 'C')

	pdf = PDF()
	pdf.alias_nb_pages()
	name="reports/"+y+"/"+x+".pdf"

	ct=datetime.datetime.now().isoformat(' ', 'seconds')
	txs=str(ct)

	pdf.add_page()
	pdf.set_font("Arial", 'B', size = 15) 
	file = open("output/"+y+"/"+x+"."+y+".report", "r") 
	for g in file:
	        pdf.multi_cell(0, 10, txt = g, border=1, align = 'L') 

	pdf.output(name)

root = Tk()
root.title('Mal-Or-Not')
root.geometry("995x510+630+250")
bg= PhotoImage(file="matrixbg.png")  

my_canvas = Canvas(root, width=200, height=100, bd=0, highlightthickness=0,bg='black')
my_canvas.pack(fill="both", expand=True)

my_canvas.create_image(0,0, image=bg, anchor="nw")
my_canvas.create_text(430,40, text="Mal-O", font=("Helvetica", 40,'bold'), fill="white")
my_canvas.create_text(580,40, text="R-Not", font=("Helvetica", 40,'bold'), fill="black")

def my_time():
    time_string = strftime('%H:%M:%S %p\n%A\n%x')
    l1.config(text=time_string)
    l1.after(1000,my_time)
my_font=('times',15,'bold')
l1=Label(my_canvas, anchor="w", justify=LEFT, font=my_font,fg='white',bg='black')
l1.grid(row=2,column=0,padx=10,pady=380, sticky='w')

my_time()

llocation=Label(my_canvas, text=location, font=my_font,fg='white',bg='black').grid(row=0,column=0,padx=10,pady=5, sticky='w')
lweather=Label(my_canvas, text=weatherf, font=my_font,fg='white',bg='black').grid(row=1,column=0,padx=10,pady=0, sticky='w')

speed=float(data.split()[1])
if speed < 100:
	my_canvas.create_text(920,30, text=data, font=("times", 15,'bold'), fill="green")
elif speed > 100 and speed <250:
	my_canvas.create_text(920,30, text=data, font=("times", 15,'bold'), fill="orange")
else:
    my_canvas.create_text(920,30, text=data, font=("times", 15,'bold'), fill="red")


def IP():
	global typeid
	typeid='ip'
	rootentry = Tk()
	rootentry.title('IP Intel')
	rootentry.geometry("350x200+670+300")
	#bg= PhotoImage(file="matrixbg.png")
	ip_canvas = Canvas(rootentry, width=200, height=100, bd=0, highlightthickness=0, bg="black")
	ip_canvas.pack(fill="both", expand=True)

	#my_canvas.create_image(0,0, image=bg, anchor="nw")
	ip_canvas.create_text(180,45, text="Enter IP Address:", font=("Helvetica", 18,'bold'), fill="white")
	entry = Entry(rootentry, font=("Helvitica",12),width=13, fg="black", bd=0)
	entry_window = ip_canvas.create_window(115,80,anchor='nw', window=entry)
	def store():
	    global inp
	    inp=entry.get()
	    print(typeid+":"+inp)
	    rootentry.destroy()
	    
	    subprocess.check_output(["./ipintel.sh", "-i", inp])
	    
	    rootip = Tk()
	    rootip.title('IP Information')
	    rootip.geometry("800x300+670+300")
	    
	    my_canvas=Canvas(rootip, bg='black', bd=0, highlightthickness=0, relief='ridge')
	    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
	    
	    with open("output/ip/"+inp+".ip.report","r") as f:
	    	data=f.read()
	    text_key= Label(my_canvas, text=data, anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='white').grid(row=0, column=0)
	    makepdf(inp,typeid,data)
	    rootip.mainloop()

	buttonentry=Button(rootentry, text="Done",font=("times",12),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=store)
	buttonentry_window = ip_canvas.create_window(145,130, anchor='nw', window=buttonentry)

	rootentry.mainloop()
	

def Domain():
	with open("usernamelocation.txt","w") as n:
		n.write(username+'\n'+location)
	subprocess.call(['python3','WhoIsInfo.py'])


def Email():
	global typeid
	typeid='email'
	rootentry = Tk()
	rootentry.title('Email Intel')
	rootentry.geometry("350x200+670+300")
	#bg= PhotoImage(file="matrixbg.png")
	email_canvas = Canvas(rootentry, width=200, height=100, bd=0, highlightthickness=0, bg="black")
	email_canvas.pack(fill="both", expand=True)

	#my_canvas.create_image(0,0, image=bg, anchor="nw")
	email_canvas.create_text(180,45, text="Enter Email Address:", font=("Helvetica", 18,'bold'), fill="white")
	entry = Entry(rootentry, font=("Helvitica",12),width=13, fg="black", bd=0)
	entry_window = email_canvas.create_window(115,80,anchor='nw', window=entry)
	def store():
	    global inp
	    inp=entry.get()
	    print(typeid+":"+inp)
	    rootentry.destroy()
	    
	    subprocess.check_output(["./email.sh",inp])
	    
	    rootemail = Tk()
	    rootemail.title('Email Information')
	    rootemail.geometry("350x210+670+300")
	    
	    my_canvas=Canvas(rootemail, bg='black', bd=0, highlightthickness=0, relief='ridge')
	    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
	    
	    with open("output/email/"+inp.split("@")[0]+".email.report","r") as f:		# I changed
	    	data=f.read()
	    text_key= Label(my_canvas, text=data, anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='white').grid(row=0, column=0)
	    newinp=inp.split("@")[0]
	    makepdf(newinp,typeid,data)

	    rootemail.mainloop()

	buttonentry=Button(rootentry, text="Done",font=("times",12),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=store)
	buttonentry_window = email_canvas.create_window(145,130, anchor='nw', window=buttonentry)

	rootentry.mainloop()

def phno():
	global typeid
	typeid='number'
	rootentry = Tk()
	rootentry.title('Phone Number Intel')
	rootentry.geometry("350x200+670+300")
	phno_canvas = Canvas(rootentry, width=200, height=100, bd=0, highlightthickness=0, bg="black")
	phno_canvas.pack(fill="both", expand=True)

	phno_canvas.create_text(180,45, text="Enter Phone Number:", font=("Helvetica", 18,'bold'), fill="white")
	entry = Entry(rootentry, font=("Helvitica",12),width=13, fg="black", bd=0)
	entry_window = phno_canvas.create_window(115,80,anchor='nw', window=entry)
	def store():
	    global inp
	    inp=entry.get()
	    print(typeid+":"+inp)
	    rootentry.destroy()
	    
	    subprocess.check_output(["sh","./number.sh", inp])
	    
	    rootphno = Tk()
	    rootphno.title('Phone Number Information')
	    rootphno.geometry("320x170+670+300")
	    
	    my_canvas=Canvas(rootphno, bg='black', bd=0, highlightthickness=0, relief='ridge')
	    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
	    
	    with open("output/number/"+inp+".number.report","r") as f:
	    	data=f.read()
	    text_key= Label(my_canvas, text=data, anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='white').grid(row=0, column=0)
	    makepdf(inp,typeid,data)

	    rootphno.mainloop()

	buttonentry=Button(rootentry, text="Done",font=("times",12),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=store)
	buttonentry_window = phno_canvas.create_window(145,130, anchor='nw', window=buttonentry)

	rootentry.mainloop()


def link():
	global typeid
	typeid='url'
	rootentry = Tk()
	rootentry.title('URL Intel')
	rootentry.geometry("350x200+670+300")
	url_canvas = Canvas(rootentry, width=200, height=100, bd=0, highlightthickness=0, bg="black")
	url_canvas.pack(fill="both", expand=True)

	url_canvas.create_text(180,45, text="Enter URL:", font=("Helvetica", 18,'bold'), fill="white")
	entry = Entry(rootentry, font=("Helvitica",12),width=13, fg="black", bd=0)
	entry_window = url_canvas.create_window(115,80,anchor='nw', window=entry)
	def store():
	    global inp
	    inp=entry.get()
	    print(typeid+":"+inp)
	    rootentry.destroy()
	    
	    subprocess.check_output(["./urlreport.sh", inp])
	    
	    rooturl = Tk()
	    rooturl.title('URL Information')
	    rooturl.geometry("280x300+670+300")
	    
	    my_canvas=Canvas(rooturl, bg='black', bd=0, highlightthickness=0, relief='ridge')
	    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
	    
	    with open("output/url/"+inp.split("/")[2]+".url.report","r") as f:
	    	data=f.read()
	    text_key= Label(my_canvas, text=data, anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='white').grid(row=0, column=0)
	    newinp=inp.split("/")[2]
	    makepdf(newinp,typeid,data)

	    rooturl.mainloop()

	buttonentry=Button(rootentry, text="Done",font=("times",12),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=store)
	buttonentry_window = url_canvas.create_window(145,130, anchor='nw', window=buttonentry)

	rootentry.mainloop()

def files():
	global typeid
	typeid='file'

	clickbrowse()

def clickentry():
	pass
	
def clickbrowse():
	rootbrowse = Tk()
	rootbrowse.title('Mal-Or-Not')
	rootbrowse.geometry("350x200+670+300")
	my_canvas1 = Canvas(rootbrowse, width=200, height=100, bd=0, highlightthickness=0, bg="black")
	my_canvas1.pack(fill="both", expand=True)
	my_canvas1.create_text(180,30, text="Mal-O-Not", font=("Helvetica", 24,'bold'), fill="white")
	
	def browseFiles():
		global inp
		inp = filedialog.askopenfilename(initialdir = os.getcwd(), title = "Select a File", filetypes = (("Text files", "*.txt*"), ("all files", "*.*")))
		subprocess.check_output(["./file.sh", inp])
		rootbrowse.destroy()		
		# text_key= Label(my_canvas, text=data, anchor="w", justify=LEFT, font='"Helvetica" 12', bg='black', fg='lime').grid(row=0, column=0)

		rootentry = Tk()
		rootentry.title('File info')
		rootentry.geometry("460x600+670+300")

		main_frame=Frame(rootentry)
		main_frame.pack(fill=BOTH, expand=1)

		my_canvas1=Canvas(main_frame, bg='black', bd=0, highlightthickness=0, relief='ridge')
		my_canvas1.pack(side=LEFT, fill=BOTH, expand=1)

		my_scrollbar=ttk.Scrollbar(main_frame, orient=VERTICAL, command=my_canvas1.yview)
		my_scrollbar.pack(side=RIGHT, fill=Y)

		my_canvas1.configure(yscrollcommand=my_scrollbar.set)
		my_canvas1.bind('<Configure>', lambda e:my_canvas1.configure(scrollregion=my_canvas1.bbox("all")))
		second_frame=Frame(my_canvas1, bg='black')
		my_canvas1.create_window((0,0), window=second_frame, anchor='nw')

		with open("output/file/"+inp.split("/")[-1].split(".")[0]+".file.report","r") as f:
			data=f.readlines()
			row=0
			col=1
			for i in data:
				text_key= Label(second_frame, text=i, font='"Helvetica" 12', bg='black', fg='white').grid(row=row, column=col, sticky='w')
				row+=1
		newinp=inp.split("/")[-1].split(".")[0]
		makepdf(newinp,typeid,data)

		rootentry.mainloop()
	
	button_explore=Button(rootbrowse, text="Browse Files",font=("times",15),width=5,padx=40, pady=10, fg='white', bg='black', bd=0, command=browseFiles)
	button_explore_window = my_canvas1.create_window(112,90,anchor='nw', window=button_explore)

	rootbrowse.mainloop()

def clickquit():
	root.destroy()

button1=Button(my_canvas, text="IP",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='black', bg='white', bd=0, command=IP, activebackground="black", activeforeground="white")
button1_window = my_canvas.create_window(300,100,anchor='nw', window=button1)

button2=Button(my_canvas, text="E-mail",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='black', bg='white', bd=0, command=Email, activebackground="black", activeforeground="white")
button2_window = my_canvas.create_window(200,240,anchor='nw', window=button2)

button3=Button(my_canvas, text="URL",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='black', bg='white', bd=0, command=link, activebackground="black", activeforeground="white")
button3_window = my_canvas.create_window(300,380,anchor='nw', window=button3)

button4=Button(my_canvas, text="Domain",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=Domain, activebackground="white", activeforeground="black")
button4_window = my_canvas.create_window(600,100,anchor='nw', window=button4)

button5=Button(my_canvas, text="Phone No.",font=("times",17,'bold'),width=7,padx=15, pady=10, fg='white', bg='black', bd=0, command=phno, activebackground="white", activeforeground="black")
button5_window = my_canvas.create_window(700,240,anchor='nw', window=button5)

button6=Button(my_canvas, text="File",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='white', bg='black', bd=0, command=files, activebackground="white", activeforeground="black")
button6_window = my_canvas.create_window(600,380,anchor='nw', window=button6)

button7=Button(my_canvas, text="Quit",font=("times",17,'bold'),width=5,padx=15, pady=7, fg='red', bg='black', bd=0, command=clickquit, activebackground="red", activeforeground="black")
button7_window = my_canvas.create_window(890,450,anchor='nw', window=button7)

root.mainloop()
